<!DOCTYPE html>
<html>
<head>
    <title>Laporan Agenda Outdoor</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h2 { margin: 0; color: #1A237E; }
        .header p { margin: 5px 0; color: #555; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; color: #333; }
        
        .badge-danger { color: red; font-weight: bold; }
        .badge-success { color: green; font-weight: bold; }
        
        .footer { margin-top: 30px; text-align: right; font-size: 10px; color: #888; }
    </style>
</head>
<body>

    <div class="header">
        <h2>Itinerary Kegiatan Outdoor</h2>
        <p>Personal Assistant Mahasiswa Rantau</p>
        <p>Dicetak pada: {{ date('d M Y, H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%">No</th>
                <th style="width: 30%">Nama Kegiatan</th>
                <th style="width: 20%">Lokasi</th>
                <th style="width: 20%">Waktu</th>
                <th style="width: 25%">Prediksi Cuaca</th>
            </tr>
        </thead>
        <tbody>
            @forelse($agendas as $index => $agenda)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $agenda->nama_kegiatan }}</td>
                <td>{{ $agenda->lokasi_kota }}</td>
                <td>
                    {{ \Carbon\Carbon::parse($agenda->waktu_mulai)->format('d M Y') }}<br>
                    <small>{{ \Carbon\Carbon::parse($agenda->waktu_mulai)->format('H:i') }} WIB</small>
                </td>
                <td>
                    @if(str_contains(strtolower($agenda->prediksi_cuaca), 'hujan') || str_contains(strtolower($agenda->prediksi_cuaca), 'petir'))
                        <span class="badge-danger">{{ $agenda->prediksi_cuaca }}</span>
                    @else
                        <span class="badge-success">{{ $agenda->prediksi_cuaca }}</span>
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="5" style="text-align: center;">Belum ada rencana kegiatan.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        &copy; 2025 Kelompok 9 WAD - Generated by System
    </div>

</body>
</html>